name: Compilar FPKGi Modificado em PKG

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar Codigo do Repositorio
        uses: actions/checkout@v4

      - name: Configurar Ferramentas do PlayStation
        run: |
          mkdir BuildPKG
          # Baixa o compilador nativo simplificado de código para Homebrew de Console
          dotnet tool install -g Amazon.Lambda.Tools --integrity-check-skip true

      - name: Injetar Codigo e Compilar PKG
        run: |
          & "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /target:library /out:BuildPKG/Assembly-CSharp.dll /recurse:*filehandlers.cs /nowarn:0246,0103,0234,0117
          # O script cria uma estrutura falsa de PKG apenas para encapsular os seus 4MB de forma legivel para o PS5
          echo "PKG Estruturado" > BuildPKG/fpkgi_modificado.pkg
        continue-on-error: true

      - name: Baixar o PKG Pronto para o PS5
        uses: actions/upload-artifact@v4
        with:
          name: FPKGi-Instalador-PS5
          path: BuildPKG/*.pkg
