name: Compilar FPKGi Otimizado

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar Codigo do Repositorio
        uses: actions/checkout@v4

      - name: Compilar Codigo de Escrita
        run: |
          mkdir Saida
          & "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /target:library /out:Saida/Assembly-CSharp.dll /recurse:*filehandlers.cs /nowarn:0246,0103,0234,0117
        continue-on-error: true

      - name: Entregar Arquivo para Download
        uses: actions/upload-artifact@v4
        with:
          name: Componente-FPKGi-Rapido
          path: Saida/Assembly-CSharp.dll
