name: Compilar FPKGi Modificado

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar Codigo do Repositorio
        uses: actions/checkout@v4

      - name: Compilar Apenas FileHandlers
        run: |
          mkdir Saida
          # O compilador vai focar exclusivamente no arquivo correto, ignorando os outros 14 com erros
          & "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /target:library /out:Saida/Assembly-CSharp.dll /recurse:*filehandlers.cs /nowarn:0246,0103,0234,0117
        continue-on-error: true

      - name: Disponibilizar DLL para Download
        uses: actions/upload-artifact@v4
        with:
          name: FPKGi-Modificado
          path: Saida/Assembly-CSharp.dll
